### ISSUE TITLE
axios package version

### ISSUE THREAD

**Issue by CoolColdUK** [Granga/etsy-ts#14]
Thanks for the useful package. I've noticed the `axios` package is out-dated. `axios-auth-refresh` latest version now uses `^1.2.2`. Is there plans to upgrading the one here?

**Comment by Granga** [comment]
Hi. 
You can try the new major version `4.x.x`, but first check out the Readme, there are some breaking changes.

**Comment by CoolColdUK** [comment]
Thank you, I'll have a look 👍
