### ISSUE TITLE
I am trying to run the example but get "Missing authorization header". What am I missing? thx!

### ISSUE THREAD

**Issue by chauey** [Granga/etsy-ts#15]

**Comment by Granga** [comment]
Hi @chauey ,

If you have updated from v3 to v4, there are some breaking changes. You can find info about them at the root Readme.

I'd say your call is missing `etsyUserId` which is used to determine the `accessToken` through your implementation of [`ISecurityDataStorage`](https://github.com/Granga/etsy-ts/blob/master/src/types/ISecurityDataStorage.ts).

**Comment by chauey** [comment]
I think I just needed other code like from the quick start to get the access token from the auth server and with the right scopes, then store the access token 1st. thx!
