### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by villanus** [Granga/etsy-ts#6]
Is this supposed to be used in node or in browser?

**Comment by Granga** [comment]
Both. It depends on `fetch` or `node-fetch`. Please see readme.

**Comment by villanus** [comment]
Sorry.  I mean how do you get around oauth scope when you want to do something like update a listing from browser?

**Comment by Granga** [comment]
Not completely sure. I think the user needs to be logged in on Etsy.
Then, the `baseUrl` set to https://etsy.com/api/v2/ajax.

```typescript
let user = (await User.getUser<IUser>({
    user_id: [userId]
}, {
    baseUrl: "https://etsy.com/api/v2/ajax"
})).results[0];
```
All this is to be executed within the page context. If you are creating web extension, it will work with 

```typescript
fetch(..., { credentials: 'include' })
```


Otherwise I have not implemented anything regarding authentication, other than API key (provides r/w authentication for your account only).

**Comment by Granga** [comment]
I just discovered something.

To protect from [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) Etsy are using token. It is generated when server renders the page. I expect it to have expiration time. Not sure of the period, but an hourly page refresh should be enough.

To be able to make *write* requests, we need to include the token in the request headers. Token is stored in `window.Etsy.csrf_nonce`.  AFAIK for chrome extensions it can be retrieved with [`tab.executeScript`](https://developer.chrome.com/extensions/tabs#method-executeScript) method.

Then, when making a request, for example with `fetch`:
```javascript
let myHeaders = new Headers();

myHeaders.append("Content-Type", "application/json");
myHeaders.append("Accept", "application/json, text/javascript, */*; q=0.01");
myHeaders.append("X-Requested-With", "XMLHttpRequest");
myHeaders.append("X-Csrf-Token", Etsy.csrf_nonce);

let myInit = {
    method: "DELETE",
    headers: myHeaders,
    credentials: "include"
};

fetch("https://www.etsy.com/api/v2/ajax/collections/MHw2MDcxNDA3Mg/listings/235367575", myInit)
    .then(response => console.log("done"));
```

Now, I just need to implement this in the wrapper.

**Comment by Granga** [comment]
If you are using this wrapper in the browser (as browser extension), now you can send the CSRF token in the axios headers.

```typescript
let csrf = Etsy.csrf_nonce;
client.Listing.updateListing({
    listing_id: 7777777,
    tags: ["my", "new", "tags"],
}, {
    axiosConfig: {
        headers: { "X-Csrf-Token": csrf }
    }
})
```
